// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechJobs.Infrastructure.Data;

#nullable disable

namespace TechJobs.Infrastructure.Migrations
{
    [DbContext(typeof(TechJobsDbContext))]
    partial class TechJobsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechJobs.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "JobSeeker"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Employer"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("TechJobs.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 6, 23, 19, 43, 44, 75, DateTimeKind.Utc).AddTicks(97),
                            Email = "kaziabu.sayeed29@gmail.com",
                            FullName = "Kazi Abu Sayeed",
                            PasswordHash = "admin12345",
                            Phone = "01681-186651",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 19, 43, 44, 75, DateTimeKind.Utc).AddTicks(99),
                            Email = "Mahmudul Hasan@gmail.com",
                            FullName = "Mahmudul Hasan",
                            PasswordHash = "mahmudul12345",
                            Phone = "01711-000002",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 6, 23, 19, 43, 44, 75, DateTimeKind.Utc).AddTicks(101),
                            Email = "jahangir.seeker@jobmail.com",
                            FullName = "Jahangir Alam",
                            PasswordHash = "jahangir_hash",
                            Phone = "01711-000003",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2025, 6, 23, 19, 43, 44, 75, DateTimeKind.Utc).AddTicks(103),
                            Email = "nasima.employer@employer.com",
                            FullName = "Nasima Begum",
                            PasswordHash = "nasima_hash",
                            Phone = "01711-000004",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2025, 6, 23, 19, 43, 44, 75, DateTimeKind.Utc).AddTicks(105),
                            Email = "abdur.employer@employer.com",
                            FullName = "Abdur Rahman",
                            PasswordHash = "abdur_hash",
                            Phone = "01711-000005",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("TechJobs.Models.User", b =>
                {
                    b.HasOne("TechJobs.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TechJobs.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
